version: '3.9'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: komediantto/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    image: komediantto/foodgram_backend:latest
    restart: always
    volumes:
      - ../data/:/app/data/
      - ../static/:/app/static/
      - ../media/:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value: