# Generated by Django 4.0.1 on 2022-02-14 07:55

from django.db import migrations, models
import receipt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[receipt.validators.validate_positive], verbose_name='Время приготовления'),
        ),
    ]
