# Generated by Django 4.0.1 on 2022-02-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipt.ingredient', verbose_name='Ингредиент'),
        ),
    ]
